bootVersion=3.5.3
depMgtVersion=1.1.7
sysGroup=com.dongpv.sns
sysName=search-service
sysVersion=0.0.1-SNAPSHOT
javaVersion=21
freefairLombokVersion=8.13.1
googleGuavaVersion=33.4.6-jre
jaxbOsgiVersion=4.0.5
apacheCommonsLang3Version=3.18.0
mapstructVersion=1.6.3
testcontainersVersion=1.20.6
nimbusJwtVersion=10.2
spotlessVersion=7.0.3
h2Version=2.2.224
jacocoVersion=0.8.12
orgJsonVersion=20250517
openfeignVersion=4.3.0
