#!/bin/sh

echo "*****Run spotless*****"

case "$OSTYPE" in
  darwin*|linux*) # macOS or Linux
    gradlew_command="./gradlew"
    ;;
  msys*) # Windows
    gradlew_command="./gradlew.bat"
    ;;
  *)
    echo "Unsupported OS: $OS_NAME"
    exit 1
    ;;
esac

if ! [ -x "$gradlew_command" ]; then
  echo "Adding execution permissions to $gradlew_command."
  chmod +x "$gradlew_command"
fi

files=$(git diff --cached --name-only --diff-filter=AMCR | grep "\.java$")

if echo "$files" | grep --quiet "\.java$"; then
  $gradlew_command spotlessApply

  echo "Add files"
  git add $files
else
  echo "No Java files found in the changes."
fi

echo "*****Done run spotless*****"